name: build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  createNpmPackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn add shelljs 
      - run: yarn run create:npm-package
      - name: Upload template
        uses: actions/upload-artifact@v1
        with:
          name: wps-game
          path: .wps-game
  
  createAndTestCRA:
    needs: createNpmPackage
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Download template
        uses: actions/download-artifact@v1
        with:
          name: wps-game
          path: ../wps-game # Put into the upper folder. create-react-app wants the current directory empty
      - name: Create CRA from downloaded template
        run: yarn create react-app --template file:../wps-game .
      - run: yarn run build
      - run: yarn run test:generators
      - run: yarn run lint
      - run: yarn run checkTs
      - run: yarn run test
      - run: yarn run cleanAndSetup
      - run: yarn run build
      - run: yarn run test:generators
      - run: yarn run lint
      - run: yarn run checkTs
  createCRAWithMultipleNodeVersions:
    needs: createNpmPackage
    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download template
        uses: actions/download-artifact@v1
        with:
          name: wps-game
          path: ../wps-game # Put into the upper folder. create-react-app wants the current directory empty
      - name: Create CRA from downloaded template
        run: yarn create react-app --template file:../wps-game .
      - run: yarn run build
      - run: yarn run test
